### ISSUE TITLE
Use serverless cloud services for running workloads

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/patterns#129]
**Describe the pattern you'd like to propose**
Serverless cloud services present an option to run workloads wherein a separate machine need not be provisioned in the cloud . 

**Describe specific emission impact from this pattern**
Serverless architectures are meant not to provision cloud servers exclusively for a specific workload or customer, but rather to use them when they are needed and then de-allocate them after the completion of workload execution. This also serves the sustainability story very effectively as servers, storage, and network bandwidth are used to their maximum utilization levels.

**References to this pattern**
(https://devblogs.microsoft.com/sustainable-software/adopting-azure-serverless-architectures-to-help-reduce-co2-emissions-part-1/)

(https://dev.to/kumo/you-thought-serverless-was-green-here-is-how-to-really-make-it-sustainable-1m0p)

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
I'll convert this
