### ISSUE TITLE
Removing Zombie Resources for VMs and Kubernetes Instances

### ISSUE THREAD

**Issue by aoifefitton** [Green-Software-Foundation/patterns#165]
**Describe the pattern you'd like to propose**
(Similar to Deleting Unused Storage Resources)

Zombies - long forgotten resources that are no longer doing useful work.

Scan for and remove any unused snoozing  or "Zombie" VM resources or cluster instances.

**Describe specific emission impact from this pattern**
Regarding SCI = ((E *I) * M) per R, both E and M will decline were this solution to be implemented.

**References to this pattern**
Reference from Vmware: https://www.sdxcentral.com/articles/news/vmware-hunts-zombies-summons-sustainability-second-wave/2020/10/ 

**Additional context**

**Comment by franziska-nttdata-hesselfeld** [comment]
Thanks for the proposed pattern, I converted it to an PR :)
