### ISSUE TITLE
Category leads to review pending issues and PRs

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/patterns#199]
Hi @aoifefitton @markus-ntt-seidl @navveenb (cc @greenhsu123)

As discussed in today's meeting, we have 20 issues and 20 PRs which haven't been turned into live patterns yet. Before we close this year, please review the ones that belong to your categories. The goal would be to find out whether there are any issues or PRs that we could turn into live patterns before the holidays. Let's discuss in our next call! In case you can't join us next time, please comment on this ticket. Thanks!

**Comment by holanita** [comment]
For some reason, I can't assign all of you. Will try again later.

**Comment by markus-ntt-seidl** [comment]
As a web lead:

- #188 :See my last comment

As a PR writer:

Done:

- #90 : Technical Writer Review
- #125 : Technical Writer Review
- #139 : Adjusted with latest SME feedback, would be done in my opinion
- #141 : Adjusted with latest SME feedback, would be done in my opinion
- #143 : Adjusted with latest SME feedback, would be done in my opinion
- #129 : Adjusted with latest SME feedback, would be done in my opinion
- #152 : Adjusted with latest SME feedback, would be done in my opinion

Second SME Feedback needed to help bring these into the main branch. Maybe someone can take over Sarah's feedback and provide a second point of view:

- #128 
- #137 
- #138

**Comment by aoifefitton** [comment]
Initial review completed on and SME review assigned to PRs:
#140
#147
#153
#154
#155
#157
#159

Would appreciate second opinion on:
#148
#151
#152

Thanks,
Aoife
