### ISSUE TITLE
Fill out Github Metadata

### ISSUE THREAD

**Issue by markus-gsf-seidl** [Green-Software-Foundation/patterns#208]
**Describe the bug**
Github Metadata on the top right is not filled out for easy access 

------
![image](https://user-images.githubusercontent.com/103509715/212840949-1b354b9c-586a-4a92-a989-ac7d235bb846.png)
 (From https://github.com/Green-Software-Foundation/green-software-patterns top right)

------
 
There should be:
* A short description of the repository (one sentence)
* A link to https://patterns.greensoftware.foundation

For example, this is a filled out version from another project

------

![image](https://user-images.githubusercontent.com/103509715/212841108-6a0dd22d-acd1-46c1-b04a-69da460508b1.png)

**Comment by russelltrow** [comment]
Metadata updated
