### ISSUE TITLE
Green Software Patterns Meeting Agenda 2023-04-11

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/patterns#227]
## Date
2023-04-11 See the time in your timezone https://everytimezone.com/s/0fdb5a75

### Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and it is the intention of the Joint Development Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [ ] Review Meeting Notices (see above)
- [ ] Review Pull Requests
- [ ] Discuss Issues
- [ ] Agenda item 1
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] ...

## Action Items
- [ ] ...

**Comment by markus-ntt-seidl** [comment]
Attended

**Comment by greenhsu123** [comment]
Attended.
