### ISSUE TITLE
Green Software Patterns Meeting Agenda 2023-05-02

### ISSUE THREAD

**Issue by Oleg-Zhymolokhov** [Green-Software-Foundation/patterns#229]
## Date
2023-05-02 - See the time in your timezone https://everytimezone.com/s/97ecedef

### Antitrust Policy
Joint Development Foundation meetings may involve participation by industry competitors, and it is the intention of the Joint Development Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

If you have questions about these matters, please contact your company counsel or counsel to the Joint Development Foundation, DLA Piper.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [ ] Review Meeting Notices (see above)
- [ ] Approve Past Meeting Minutes
- [ ] Review Pull Requests
- [x] Discuss Issues
- [ ] ...
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
None today

## Action Items

- [ ] Peter taking action on building of workshop - to set time with Asim
- [x] Asim @jawache to set up new Green Cloud Exam repo (or give permissions to @adamj89)
- [ ] Exam Group DL to be created
- [ ] Cam @camcash17  to work on exam objectives
- [ ] Asim @jawache to work with LF to connect with exam team - will connect LF with @adamj89 
- [ ] Adam to compare Exam costs with Pearson etc?
- [ ] Split of PM responsibilities between @Oleg-Zhymolokhov / @adamj89 
- [ ] Create a slide deck for the principles training - @jawache to provide archive copy to base new slides on.

**Comment by adamj89** [comment]
Attendees:
Adam Jackson @adamj89 
Asim Hussain (chairing today) @jawache 
Cameron Casher @camcash17 
Daniel Lazaro Cuadrado 
Markus Saidl @markus-ntt-seidl 
Peter Wadsworth 
Tammy McClellan @tmcclell

**Comment by adamj89** [comment]
Discussion Points:

Catalogue Top 10 Patterns
Question: How do we measure impact / grade top 10. Tammy/Asim suggest SCI. 

*Prioritisation workshops*
_within each category_
- Web
- ML/AI
- Cloud



*Group Comments*
(AH) The mechanism in which the workshop should run to be decided by the WG.
(PW) Are we happy with the patterns we have
(MS) No, too many overlapping patterns. Need more structure. 
(DC) Should review the categorisation - some cloud categories for example are generally applicable. 


*Exam Project*

*Actions*

- [ ] Peter taking action on building of workshop - to set time with Asim
- [ ] Asim @jawache to set up new Green Cloud Exam repo (or give permissions to @adamj89)
- [ ] Exam Group DL to be created
- [ ] Cam @camcash17  to work on exam objectives
- [ ] Asim @jawache to work with LF to connect with exam team - will connect LF with @adamj89 
- [ ] Adam to compare Exam costs with Pearson etc?
- [ ] Split of PM responsibilities between @Oleg-Zhymolokhov / @adamj89 
- [ ] Create a slide deck for the principles training - @jawache to provide archive copy to base new slides on.
