### ISSUE TITLE
2023 05 09 - Green Software Patterns Agenda

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/patterns#230]
## Date
2023 05 09 - 1.30pm UTC - See the time in your timezone https://everytimezone.com/s/a8399b00

### Antitrust Policy
Linux Foundation meetings involve participation by industry competitors, and it is the intention of the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws.

Examples of types of actions that are prohibited at Linux Foundation meetings and in connection with Linux Foundation activities are described in the Linux Foundation Antitrust Policy available at http://www.linuxfoundation.org/antitrust-policy. If you have questions about these matters, please contact your company counsel, or if you are a member of the Linux Foundation, feel free to contact Andrew Updegrove of the firm of Gesmer Updegrove LLP, which provides legal counsel to the Linux Foundation.

### Recordings
GSF project meetings may be recorded for use solely by the GSF team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

### Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.

Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

## Agenda
- [x] Convene & Roll Call (5mins)
- [x] Review Meeting Notices (see above)
- [x] Approve Past Meeting Minutes
- [x] Discuss exam progress
- [x] Workshop Progress (Peter)
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items (Carried Over)

- [x]  Peter taking action on building of workshop - to set time with Asim
- [ ]  Exam Group DL to be created
- [x]  Cam @camcash17 to work on exam objectives
- [ ]  Asim @jawache to work with LF to connect with exam team - will connect LF with @adamj89
- [x]  Adam to compare Exam costs with Pearson etc?
- [ ]  Split of PM responsibilities between @Oleg-Zhymolokhov / @adamj89
- [ ]  Create a slide deck for the principles training - @jawache to provide archive copy to base new slides on.
- [ ] Access to list of people who have completed the training @jawache

**Comment by greenhsu123** [comment]
Attended

**Comment by adamj89** [comment]
Attended

**Comment by ccasher** [comment]
Attended

**Comment by adamj89** [comment]
Also in attendance:
@jawache 
Daniel Lazaro Cuadrado
Peter Wadsworth
Swapnil Gupta
@tmcclell

**Comment by adamj89** [comment]
Minutes

Exam - Asim discussed LF exam progress. Asim to connect to Adam. Likely to stay with LF for examinations. Cam has learning criteria - needs to be shared with Anne. Adam has set up new repo: [Green-Software-Foundation/green-cloud-exam: Creating a new exam to recognise Green Software Practitioners (github.com)](https://github.com/Green-Software-Foundation/green-cloud-exam). 
Cam wants to work with other organisations. Information gathering.
Book not to be directly used but alignment to themes. Which books should we reference as a guide for the exam?

Questions for the exam
Exam Platform
Certification Badges
Practice Platform
Where will the syllabus be posted? 
Who is it aimed at? (Cloud Software Engineer)

Adam to dig around original materials/learning objectives. https://raw.githubusercontent.com/Green-Software-Foundation/green-software-principles/dev/Principles/carbon.md?token=GHSAT0AAAAAAB5AFMX5UUKMXWW4V3ZDC7MEZC2J4MQ

Asim shared Blooms Taxonomy - planning kit: https://github.com/Green-Software-Foundation/green-software-principles/blob/dev/blooms-taxonomy.pdf

Cam: Incorporate high level themes from training course. 

Sarah: Use principles as sections


___



Patterns

Peter Wadsworth actively starting workshop prep next week.
