### ISSUE TITLE
Serveless DB pattern 

### ISSUE THREAD

**Issue by GustavoGuimaraes86** [Green-Software-Foundation/patterns#249]
Description:
--------------
With the advent of the cloud and with it the introduction of serverless computing, there is the opportunity to share resources, increase the utilization of the underlying hardware and only pay for the actual use - not for the potential idle hardware. This usage pattern should also be adopted for storing data in databases.

Solution: 
--------------
By select a Serveless/shared tenant DB, the DB load will increase or decrease by the given demand. This saves resources without impacting the performance.

SCI Impact: 
-------------
E: energy usage = Only use the energy you use for computation. Avoid having resources consume energy while being idle. 

Assumptions: 
--------------
E: energy usage = Only use the energy you use for computation. Avoid having resources consume energy while being idle. 
ondemand database offering exists (AWS serverless aurora, MS Azure sql serverless tier, ...)

**Comment by markus-gsf-seidl** [comment]
Hi!

Thanks for your submission!

There is already a pattern for this in the dev branch (not published on main, though): https://github.com/Green-Software-Foundation/patterns/blob/dev/docs/catalog/cloud/use-serverless.md which covers all services.

**Comment by markus-gsf-seidl** [comment]
@russelltrow
This would also need to be closed, if the PR is also closed?
