### ISSUE TITLE
Series of workshops to restart and reshape patterns

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/patterns#258]
Peter Wadsworth has put himself forward to run a series of workshops to help us restart and reshape the Green Software Patterns project.

* Help us build design challenges around the patterns.
* Identify typical people / situations where a certain pattern would be use. 
* Join interesting patterns together. 
* Help us with the presentation of those patterns and how they are packaged up.

# Relevant Discussions

* https://github.com/Green-Software-Foundation/patterns/discussions/224
* https://github.com/Green-Software-Foundation/patterns/issues/232#issuecomment-1559401867
* https://github.com/Green-Software-Foundation/patterns/issues/238#issuecomment-1598858010

# Artefacts

* https://miro.com/app/board/uXjVNRt8URA=/?share_link_id=338555000376
* https://docs.google.com/document/d/16RiTA0ZYQ36d1d5iS8zEnBdTXnTMM-AxvlBjTXmiChE/edit#heading=h.listqb403abt

# Actions

- [x] Decide how we want to proceed with the workshop
- [x] GSF to determine how to engage with Peter - As an individual or through his employer
- [x] @russelltrow follow-up with Pete and get him into the next project call
- [x] Draft one-pager to share with GSF members
- [x] Pete & Russ draft workshop program outline
- [ ] Send a pre-workshop Discovery survey to participants
- [ ] Prepare a workshop pre-read

**Comment by russelltrow** [comment]
Spoke with Pete yesterday and we have started planning. First step is putting together a one-pager that we can use as a flyer to recruit interested participants from across the GSF.

I'll share a draft in the next meeting (if not before)

**Comment by adamj89** [comment]
Discussed in the meeting 2023-11-21

@russelltrow to give an update on progress in the next call on 2023-12-05

@daniel Lazaro has asked for date clarifications. Will this be post-Carbonhack 24?

**Comment by russelltrow** [comment]
In this week's project call we came to consensus on the the following timings:

  * First workshop Wednesday 17th
  * At 15:00 GMT
  * 2 hours long
  * Further workshops at the same time in the following weeks

**Comment by russelltrow** [comment]
Today I have been coordinating with the workshop facilitator and I can confirm that the workshops will take place:

* Wednesday 24 January 2024
* Wednesday 31 January 2024
* Wednesday 7 February 2024
* Wednesday 14 February 2024

Each workshop will start at 16:00 GMT and run for 2 hours.

Pete cannot do the 17th so we've pushed the first workshop back to the 24th

**Comment by russelltrow** [comment]
Workshops have now been completed. Next step is to create reports for the Patterns project team and GSF members.

I will update the wiki page: https://github.com/Green-Software-Foundation/patterns/wiki/Patterns-Strategy-workshops-%E2%80%90-Jan-2024

Expect to present the project team report on 12 March
