### ISSUE TITLE
2023-11-21 - Green Software Principles & Patterns Agenda

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/patterns#281]
2023-11-21 - 15:30 UTC - See the time in your timezone https://everytimezone.com/s/b6822e5f

## Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

### Previous Meeting

* https://github.com/Green-Software-Foundation/patterns/issues/278

## Heads up
- @russelltrow paternity leave (Mid November)

## Agenda
- [x] Convene & Roll Call
- [x] OKR & KPI updates
- [ ] Review the agenda and suggest new agenda points
- [ ] Resolve meeting scheduling conflict with Real Time Cloud
- [ ] Issues
- [ ] Pull Requests
- [ ] Discussions
- [ ] AOB, Q&A & Adjourn

## OKR & KPI updates

**Principles**
* 1 million people have enrolled in one of our training courses: 65,364
* 100K certified Green Software Practitioners by end of 2023: 54,102

**Patterns**
* 50 live
* GitHub Stars 48 (up 1)

### Principles

- [ ] https://github.com/Green-Software-Foundation/learn/issues/198
- [ ] https://github.com/Green-Software-Foundation/learn/issues/197
- [x] https://github.com/Green-Software-Foundation/learn/issues/185  - With GSF Communications team
  - [x] https://github.com/Green-Software-Foundation/learn/issues/189

### Patterns

- [x] https://github.com/Green-Software-Foundation/patterns/issues/258
  - [x] https://miro.com/app/board/uXjVNRt8URA=/?share_link_id=338555000376
- [x] https://github.com/Green-Software-Foundation/patterns/issues/260 - Making good progress!
- [x] [Contributor recruitment](https://docs.google.com/document/d/123ltvXcrgpxKgCuYZAxDVibSEv4BOpLS_Q9AgR445cE/edit#heading=h.listqb403abt)
- [x] Do we want to start assessing contributions again?
  - [ ] AVEVA - Technical & UX
  - [ ] Mastercard
  - [ ] [Others](https://github.com/Green-Software-Foundation/patterns/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement)
  - [ ] Siemens
  - [ ] Shell
- [ ] Developing Patterns Case Studies and/or Use Cases

### Principles

- [ ] https://github.com/Green-Software-Foundation/learn/pull/204

### Patterns

- [ ] 4 [Ready to Merge](https://github.com/Green-Software-Foundation/patterns/pulls?q=is%3Apr+is%3Aopen+label%3A%22Ready+to+Merge%22)
- [ ] 10 in [SME review](https://github.com/Green-Software-Foundation/patterns/pulls?q=is%3Apr+is%3Aopen+label%3A%22SME+Review%22+-label%3A%22blocked%22)
- [X] 0 in [Initial review](https://github.com/Green-Software-Foundation/patterns/pulls?q=is%3Apr+is%3Aopen+label%3A%22Initial+Review%22+-label%3A%22blocked%22+)
- [ ] 2 are [blocked](https://github.com/Green-Software-Foundation/patterns/pulls?q=is%3Apr+is%3Aopen+label%3Ablocked)

**Comment by adamj89** [comment]
apologies recieved from @markus-gsf-seidl

**Comment by franziska-warncke** [comment]
Attended

**Comment by pdematos12** [comment]
Attended

**Comment by kapokasa** [comment]
Attended

**Comment by kapokasa** [comment]
Attended

**Comment by sk16-dev** [comment]
Attended

**Comment by adamj89** [comment]
Note: 
Conversation about journey from LF course into the "what next" content

50k+ completions of GSP > how do we continue the learning journey. How do we get folks onto next steps. How do we connect with the patterns?

@adamj89 shared challenge with disconnect after course.

**Comment by adamj89** [comment]
@NAMRATA-WOKE shared thoughts on future assessment / possible exam and timelines for implementation.

**Comment by NAMRATA-WOKE** [comment]
Sean from Microsoft suggested: Patterns 'How-to Guide' 
- if practitioners are looking to assess existing applications based on the GSP and existing patterns catalog, how can they go about doing that?
