### ISSUE TITLE
Moving to Zoom for project calls

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/patterns#288]
Are there any objections if we move the Principles & Patterns project call to Zoom?

The GSF have received requests from multiple Member Organisations to use Zoom as Google Meet is discouraged. Zoom is already used by the majority of Working Groups and Projects.

**Comment by russelltrow** [comment]
@greenhsu123 this was discussed in the previous project call (https://github.com/Green-Software-Foundation/patterns/issues/284) and the consensus was actually Microsoft Teams would be more suitable than Zoom as it was the default platform for all the attendees. Does this work for you?

Could other team members please let me know which would be your preferred meeting platform:

- [ ] Google Meet
- [ ] MS Teams
- [ ] Zoom

**Comment by greenhsu123** [comment]
MS Teams won't work for GS unfortunately. Only approved platform for us is Zoom.

**Comment by russelltrow** [comment]
Agreed we will move to Zoom going forward.

@seanmcilroy29 could you help us with this please?

**Comment by seanmcilroy29** [comment]
@russelltrow - Meeting schudule updated to Zoom and new invites sent
