### ISSUE TITLE
Decision on January 2024 meeting

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/patterns#292]
Our first P&P meeting of 2024 is scheduled for Tuesday 2nd January. As this is so close to New Year would the group like to:

- [x] Reschedule to Tuesday 9th January
- [ ] Cancel the meeting
- [ ] Leave on 2nd January

Please let me know your thoughts. Unless I hear otherwise the meeting will go ahead on 2nd January.

**Comment by greenhsu123** [comment]
Reschedule to the 9th, please!

**Comment by russelltrow** [comment]
Agreed in today's meeting that we will reschedule to Jan 9th
