### ISSUE TITLE
2024-05-07 Green Software Principles & Patterns Agenda

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/patterns#315]
## Date
2024-05-07 - 14:00 UTC - See the time in your timezone https://everytimezone.com/s/3d531869

## Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

### Previous Meeting

Notes from the previous meeting: https://github.com/Green-Software-Foundation/patterns/issues/314

## Agenda
- [x] Convene & Roll Call
- [x] Review the agenda and suggest new agenda points
- [x] Green Software for Practitioners
- [ ] Green Software Patterns
- [ ] AOB, Q&A & Adjourn

## Green Software for Practitioners

* 85,429 completions

- [x] https://github.com/Green-Software-Foundation/learn/issues/173 & https://github.com/Green-Software-Foundation/learn/issues/225
  - [x] Reviewing https://github.com/Green-Software-Foundation/learn/pull/227
- [x] https://github.com/Green-Software-Foundation/learn/issues/221
  - [x] Finalise [project canvas](https://miro.com/app/board/uXjVNkWXfC0=/?share_link_id=825890314860)

## Green Software Patterns

* 59 patterns live ([v1.2.0](https://github.com/Green-Software-Foundation/patterns/releases/tag/v1.2.0))

- [ ] [Open Pull Requests](https://github.com/Green-Software-Foundation/patterns/pulls)

## Use Cases

- [ ] https://github.com/Green-Software-Foundation/patterns/issues/297

**Comment by franziska-warncke** [comment]
Attended

**Comment by russelltrow** [comment]
## Meeting Notes

## Green Software for Practitioners

### Translations

* Discussed @franziska-warncke Pull Request for a German translation of the course
  * https://github.com/Green-Software-Foundation/learn/pull/227
* @russelltrow agreed to reach out to Carolin to see if should could provide a content review.

### Green Guides

* Worked through the project canvas to define the project's key details
  * https://miro.com/app/board/uXjVNkWXfC0=/?share_link_id=778187260993
  * [PDF of Miro board](https://github.com/Green-Software-Foundation/patterns/files/15238169/GSP.-.Green.Guides.pdf)
* Finalised the canvas and agreed to kick-off the project after sharing the canvas with the project team
