### ISSUE TITLE
2024-06-18 Green Software Principles & Patterns Agenda

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/patterns#321]
## Date
2024-06-18 - 14:00 UTC - See the time in your timezone https://everytimezone.com/s/ab85f7c5

## Roll Call 
Please *add a comment* to this issue during the meeting to denote attendance.
Any untracked attendees will be added by the GSF team below:
- Full Name, Affiliation, (optional) GitHub username

### Previous Meeting

Notes from the previous meeting: https://github.com/Green-Software-Foundation/patterns/issues/315

## Agenda
- [x] Convene & Roll Call
- [x] Review the agenda and suggest new agenda points
- [x] Green Software for Practitioners
- [ ] Green Software Patterns
- [ ] AOB, Q&A & Adjourn

## Green Software for Practitioners

* 90,288 completions

- [x] Update on HSBC eLearning course
- [x] https://github.com/Green-Software-Foundation/learn/issues/173
- [x] https://github.com/Green-Software-Foundation/learn/issues/225
- [x] https://github.com/Green-Software-Foundation/learn/issues/221
  - [x] [Reviewing the guide template](https://hackmd.io/@gsf-learn/green-guide-template)
  - [x] [Defining the DevOps Engineer persona](https://github.com/Green-Software-Foundation/learn/issues/228)

## Green Software Patterns

* 59 patterns live ([v1.2.0](https://github.com/Green-Software-Foundation/patterns/releases/tag/v1.2.0))

- [ ] https://github.com/Green-Software-Foundation/patterns/issues/265
- [ ] [Patterns requiring initial review](https://github.com/Green-Software-Foundation/patterns/pulls?q=is%3Apr+is%3Aopen+-label%3A%22blocked%22+label%3A%22initial+review%22)

## Use Cases

- [ ] https://github.com/Green-Software-Foundation/patterns/issues/297

**Comment by llhardy1A** [comment]
attended

**Comment by russelltrow** [comment]
Attended

**Comment by greenhsu123** [comment]
Attended.

**Comment by russelltrow** [comment]
# Meeting Notes

## Green Guides

* Reviewed the [guide template document](https://hackmd.io/@gsf-learn/green-guide-template)
  * Spoke about how to connect the specific persona content (e.g. DevOps Engineer) to other concepts outside of Green Software Engineering that the person might be more familiar with. e.g. GreenOps, FinOps
  * Spoke about the https://opentelemetry.io/ project and it's relevancy to DevOps Engineers
  * Expanded the "Take it further section" with an additional call to action about contributing to relevant projects and also linking to useful advocacy materials such as presentation decks
* Agreed to distribute the template to the project mailing list one final time before finalising and starting to build the DevOps one

## Actions

- [ ] @russelltrow distribute green guide template to mailing list for any further feedback
- [ ] @russelltrow @greenhsu123 finalise template next week
- [ ] @greenhsu123 start drafting the DevOps Engineer guide once template finalised
