### ISSUE TITLE
[Cloud Engineer] Use software patterns and architectures that best support data access and storage patterns

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/patterns#53]
**Describe the pattern you'd like to propose**
Intent: Understand how data is used within your workload, consumed by your users, transferred, and stored. Select technologies to minimize data processing and storage requirements.

***
**Describe the pattern you'd like to propose**
This pattern involves monitoring and analysing your data access and storage access selecting technologies which minimise processing and storage requirements.
This can be achieved in a number of ways, including: 
Using efficient file formats such as Parquet for storage to prevent unnecessary  processing
Using technologies that work natively with compressed data
Using the optimal database engine to support your dominant query pattern
Ensuring your database index designs support efficient query execution
Using network protocols that reduce the consumption of network capacity

**Describe specific emission impact from this pattern**
By minimising data processing and storage requirements you consume less energy and resources.
In terms of the SCI impact, this means both M (embodied carbon) and E (energy) are reduced, leading to a lower overall score.

**References to this pattern**
https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/use-software-patterns-and-architectures-that-best-support-data-access-and-storage-patterns.html

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by holanita** [comment]
edited version has been added, issue updated

**Comment by markus-ntt-seidl** [comment]
I'm converting these
