### ISSUE TITLE
[Cloud Engineer] Optimize impact on customer devices and equipment

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/patterns#56]
**Describe the pattern you'd like to propose**
Intent: Understand the devices and equipment your customers use to consume your services, their expected lifecycle, and the financial and sustainability impact of replacing those components. Implement software patterns and architectures to minimize the need for customers to replace devices and upgrade equipment. For example, implement new features using code that is backwards compatible with older hardware and operating system versions, or manage the size of payloads so they don’t exceed the storage capacity of the target device.

***
**Describe the pattern you'd like to propose**
This pattern involves understanding the usage behaviours of your customers, including what hardware they use to consume your software, and optimising your software design and architecture to extend the life of their devices. This means doing customer research to understand what devices they are using and running tests on managed test farms to understand the impact of software changes. 
Some of the ways you can improve the performance of software under different conditions:
If your users rely on low network bandwidth or internet latency, ensure your software runs efficiently under these conditions
If user devices are old or low-performance, run higher-intensity activities server side or use application streaming to improve performance
If local storage is limited, use segmentation and pagination to manage payloads 
If older hardware or operating systems are being used, implement new features using code that is backwards compatible  
If data transfer is limited, pre-process data payloads to reduce local processing requirements    

**Describe specific emission impact from this pattern**
Increasing the lifetime usage of hardware reduces the environmental impact of the device and increasing the efficiency of the software reduces the energy consumed when running processes.
In terms of the SCI impact, this means both M (embodied carbon) and E (energy) are reduced, leading to a lower overall score.

**References to this pattern**
https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/optimize-impact-on-customer-devices-and-equipment.html

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by holanita** [comment]
edited version has been added, issue updated

**Comment by markus-ntt-seidl** [comment]
I'm taking over.
