### ISSUE TITLE
[Web] Keep request counts low and transfer sizes small

### ISSUE THREAD

**Issue by dubrie** [Green-Software-Foundation/patterns#58]
**Describe the pattern you'd like to propose**
Requests for CSS and JavaScript files are render-blocking by default. In other words, browsers can't render content to the screen until all CSS and JavaScript requests are finished. If any of these files are hosted on a slow server, that single slow server can delay the entire rendering process. See [Optimize your JavaScript](https://web.dev/fast#optimize-your-javascript), [Optimize your third-party resources](https://web.dev/fast#optimize-your-third-party-resources), and [Optimize your CSS](https://web.dev/fast#optimize-your-css) to learn how to only ship the code that you actually need.

**Describe specific emission impact from this pattern**
Reduced energy consumption by reducing download size and increased page performance

**References to this pattern**
https://web.dev/resource-summary/

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by markus-ntt-seidl** [comment]
Taking over
