### ISSUE TITLE
[Cloud Engineer] Remove or refactor workload components with low or no use

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/patterns#61]
**Describe the pattern you'd like to propose**
Intent: Monitor workload activity to identify changes in utilization of individual components over time. Remove components that are unused and no longer required, and refactor components with little utilization, to limit wasted resources.

***
**Describe the pattern you'd like to propose**
This pattern involves monitoring and analysing workload activity so that components that are surplus to requirements can be removed and those that are underused can be refactored. Analysing factors such as transaction flow and API calls to determine the load on functional components will help you identify components that are under-utilised or unused. Underutilised components can either be refectory or consolidated with other resources.

**Describe specific emission impact from this pattern**
This removal or refactoring of resources results in more efficient process that consume less, and less waste which means hardware usage can be reduced.
In terms of the SCI impact, this means both M (embodied carbon) and E (energy) are reduced, leading to a lower overall score.

**References to this pattern**
https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/remove-or-refactor-workload-components-with-low-or-no-use.html

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by holanita** [comment]
edited version has been added, issue updated

**Comment by markus-ntt-seidl** [comment]
I'll do it.
