### ISSUE TITLE
[Cloud-Engineer] Region Selection

### ISSUE THREAD

**Issue by holanita** [Green-Software-Foundation/patterns#74]
**Describe the pattern you'd like to propose**
"Choose Regions near Amazon renewable energy projects and Regions where the grid has a published carbon intensity that is lower than other locations (or Regions)."

****
**Describe the pattern you'd like to propose**
This pattern involves the selection of regions where workloads are implemented that are close to Amazon renewable energy projects and where the grid has a lower carbon intensity.

**Describe specific emission impact from this pattern**
Choosing regions based on proximity or carbon intensity means a lower energy expenditure both to transfer the workloads and also in terms of the embodied carbon involved in the hardware required to transmit it.
In terms of the SCI impact, this means both M (embodied carbon) and E (energy) are reduced, leading to a lower overall score.

**References to this pattern**
https://docs.aws.amazon.com/wellarchitected/latest/sustainability-pillar/region-selection.html

**Additional context**
Add any other context or screenshots about the proposed pattern here.

**Comment by holanita** [comment]
@dubrie @jawache editor's version added at the bottom

**Comment by markus-ntt-seidl** [comment]
I assume this can be converted into a PR?
I'll do it and you let me know if this was not allowed :)
